name: Publish Python Package

on:
  release:
    types:
      - created

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: release
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install Poetry
        run: curl -sSL https://install.python-poetry.org | python -

      - name: Build and publish package
        run: |
          poetry config pypi-token.pypi ${{ secrets.PYPI_TOKEN }}
          poetry build
          poetry publish
        env:
          POETRY_PYPI_TOKEN: ${{ secrets.PYPI_TOKEN }}
